#!/bin/sh
# $Id$

STATUS_DIR=/var/run/control

for FACILITY in "$@"; do
	FACILITY="${FACILITY//\//_}"

	FILE="$STATUS_DIR/$FACILITY"
	if [ -s "$FILE" ]; then
		STATUS="`cat "$FILE"`"
		if [ -n "$STATUS" -a "$STATUS" != unknown ]; then
			/usr/sbin/control "$FACILITY" "$STATUS"
		fi
	fi
	rm -f "$FILE"
done
