#!/bin/sh
# $Id$

STATUS_DIR=/var/run/control

for FACILITY in "$@"; do
	[ -n "${FACILITY//*\/*/}" ] || FACILITY=`echo "$FACILITY" |tr / _`

	rm -f "$STATUS_DIR/$FACILITY"
	/usr/sbin/control "$FACILITY" >"$STATUS_DIR/$FACILITY" ||
		rm -f "$STATUS_DIR/$FACILITY"
done
