#!/bin/sh
# $Id$

STATUS_DIR=/var/run/control

for FACILITY in "$@"; do
	FACILITY="${FACILITY//\//_}"

	FILE="$STATUS_DIR/$FACILITY"
	rm -f "$FILE"
	/usr/sbin/control "$FACILITY" status > "$FILE" || rm -f "$FILE"
done
