#!/bin/sh
# $Id$

echo_error()
{
	echo "${0##*/}: $*" >&2
}

define()
{
	local arg=$(printf %s "$3" |sed -e 's/["$`\]/\\&/g')
	eval "$1_$2=\"$arg\""
}

lookup()
{
	eval "echo \$$1_$2"
}

validate()
{
	echo "$1" | grep -q '^[a-z0-9_]*$'
}

NAME_LIST=
register()
{
	[ -z "`lookup REGISTERED "$1"`" ] || return
	define REGISTERED "$1" yes
	[ -z "$NAME_LIST" ] && NAME_LIST="$1" || NAME_LIST="$NAME_LIST $1"
}

new_fmode()
{
	register "$1"
	define NAME_TO_FMODE "$1" "$2"
	define NAME_TO_OWNER "$1" "$3:$4"
	define FMODE_OWNER_TO_NAME "$2_$3_$4" "$1"
}

new_subst()
{
	register "$1"
	define NAME_TO_REGEX "$1" "$2"
	define NAME_TO_SUBST "$1" "$3"
}

new_help()
{
	register "$1"
	define HELP_TO "$1" "$2"
}

stat_file()
{
	local PATHNAME="$1" BASEPATH

	BASEPATH="`echo "$PATHNAME" | sed 's,/[^/]*$,,'`"
	find "$BASEPATH" -path "$PATHNAME" -maxdepth 1 -printf '%m_%u_%g'
}

control_list()
{
	echo "$NAME_LIST"
}

control_help()
{
  	local NAME

	for NAME in $NAME_LIST; do
		echo -n "$NAME: "
		lookup HELP_TO "$NAME"
	done
}

control_fmode_status()
{
	local FILE="$1" STAT NAME

	STAT="`stat_file "$FILE"`"
	NAME="`validate "$STAT" && lookup FMODE_OWNER_TO_NAME "$STAT"`"
	if [ -n "$NAME" ]; then
		echo "$NAME"
	else
		echo "unknown"
	fi
}

control_fmode()
{
	local FILE="$1" REQUEST="$2" FMODE= OWNER=

	case "$REQUEST" in
	help)
		control_help
		;;
	list)
		control_list
		;;
	status)
		control_fmode_status "$FILE"
		;;
	*)
		if validate "$REQUEST"; then
			FMODE="`lookup NAME_TO_FMODE "$REQUEST"`"
			OWNER="`lookup NAME_TO_OWNER "$REQUEST"`"
		fi
		if [ -z "$FMODE" -o -z "$OWNER" ]; then
			echo_error "Invalid mode: $REQUEST"
			return 1
		fi
		if [ "`control_fmode_status "$FILE"`" = "$REQUEST" ]; then
			return
		fi
		chown "$OWNER" "$FILE" && chmod "$FMODE" "$FILE" || return 1
		;;
	esac
}

control_subst_status()
{
	local FILE="$1" NAME REGEX

	for NAME in $NAME_LIST; do
		REGEX="`lookup NAME_TO_REGEX "$NAME"`"
		[ -n "$REGEX" ] || continue
		if grep -Eq "$REGEX" "$FILE"; then
			echo "$NAME"
			return
		fi
	done
	echo "unknown"
}

control_subst()
{
	local FILE="$1" REQUEST="$2" SUBST

	case "$REQUEST" in
	help)
		control_help
		;;
	list)
		control_list
		;;
	status)
		control_subst_status "$FILE"
		;;
	*)
		SUBST="`validate "$REQUEST" && lookup NAME_TO_SUBST "$REQUEST"`"
		if [ -z "$SUBST" ]; then
			echo_error "Invalid mode: $REQUEST"
			return 1
		fi
		if [ "`control_subst_status "$FILE"`" = "$REQUEST" ]; then
			return
		fi
		subst "$SUBST" "$FILE" || return 1
		;;
	esac
}

is_builtin_mode()
{
	case "$1" in
	help|list|status|'')
		return 0
		;;
	esac
	return 1
}

[ -n "$*" ] || set - status
