.\" -*- mode: troff; coding: utf8 -*-
.TH CONTROL 8 "18 April 2003" "Openwall Project"
.hy 0
.SH НАЗВАНИЕ
\fBcontrol\fR \- управление компонентами системы
.SH ФОРМАТ ВЫЗОВА
.B control
[ \fIFACILITY\fR [\fBhelp\fR|\fBlist\fR|\fBstatus\fR|\fBsummary\fR|\fISTATUS\fR] ]
.SH ОПИСАНИЕ
.B control
предоставляет унифицированный интерфейс для управления компонентами системы.
.PP
Основное предназначение данной программы - управление критичными
системными компонентами, непродуманная настройка которых может
представлять опасность для системы в целом. Она позволяет включать,
отключать, а также управлять типовыми настройками системных
компонентов независимо от процедуры установки пакетов.
.PP
При запуске без параметров
.B control
выдает список известных компонентов с их существующими и доступными
настройками.
.PP
При указании названия компонента
.I FACILITY
.B control
может вывести информацию о компоненте, а при дополнительном указании команд:
.B list
\- доступные настройки;
.B help
\- краткую справку;
.B status
\- текущее состояние компонента (выполняется по умолчанию), или же
изменить это состояние в соответствии с параметром
.IR STATUS .
.SH ФАЙЛЫ
.ad l
.in +4
.ti -4
.I /etc/control.d/facilities/
\- каталог со скриптами управления компонентами для
.B control
.br
.ti -4
.I /etc/control.d/functions
\- библиотека общих функций для этих скриптов
.in -4
.ad b
.SH ИСТОРИЯ СОЗДАНИЯ
Программа
.B control
была разработана для и впервые появилась в Openwall GNU/*/Linux 0.1.
.SH АВТОР
Solar Designer <solar@owl.openwall.com>
.SH СМ. ТАКЖЕ
.BR chkconfig (8),
.BR control-dump (8)
